version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: content_management
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    command: >
      bash -c "npm run build && npm run migration:run && npm run seed:run && npm run start:prod"


volumes:
  pgdata:
