version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: content_management
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
